import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {Reflector} from 'three/addons/objects/Reflector.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {MarchingCubes} from 'three/addons/objects/MarchingCubes.js';
import {createElement} from './geometry.js';
import * as MaterialLibrary from './materials.js';
import {createMaterials,updateMaterials,createVolumeMaterial} from './materials.js';
import {TransitionSystem} from './transitions.js';
import {MotionController,InteractionBus} from './motion.js';

const $=s=>document.querySelector(s), clamp=THREE.MathUtils.clamp;
const qaMode=new URLSearchParams(location.search).has('qa');
const state={mode:'world',theme:'tidal',selected:'A01',family:'all',search:'',time:0,motion:true,bloom:true,quality:'high',fps:0,drag:null,simulation:null,seedStart:-100,seed:null};
const palette={tidal:['#132a46','#7fadc9','#d7e5f1'],opal:['#385452','#c5d7b4','#f4e5cd'],moss:['#172c24','#718f68','#d8d9ad'],obsidian:['#101725','#566989','#b8b9dc'],aurora:['#263142','#b5a6cd','#c1ece0'],amber:['#41382a','#c9a67b','#f1dcbc']};
let catalogue=[],compositions=[],physics=null, optics=null,materials,scene,camera,renderer,composer,bloomPass,controls,content,environment,water,backdrop,caustics,environmentPMREM;
const waterImpulses=[];
const motions=[],animated=[],pickables=[],raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),bus=new InteractionBus();
bus.addEventListener('touch',e=>{waterImpulses.push({x:e.position.x,z:e.position.z,start:state.time,strength:e.strength});if(waterImpulses.length>8)waterImpulses.shift();const f=state.simulation?.fluid;if(f)f.addImpulse([0,.35,0],2,[.08,.2,.05]);});
const clock=new THREE.Clock(),dummy=new THREE.Object3D(),v3=new THREE.Vector3(),p3=new THREE.Vector3();
let backdropReady=Promise.resolve();
let transitionSystem=null,transitionHandle=null,transitionId=null;
let reflectionSerial=0;
let cameraTween=null,frameCount=0,fpsClock=0,resizeObserver,selectedObject;
const fallbackNames={A:'Gel bodies',B:'Controls',C:'Panels',D:'Structures',E:'Liquid',F:'Films',G:'Particles',H:'Fields',I:'Light',J:'Environments',K:'Contact',L:'Transitions',N:'Nature accents'};

function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function fail(error){console.error(error);$('#loading').classList.add('done');$('#error').hidden=false;$('#error').textContent=`The 3D preview could not start: ${error.message}. Open this folder with the included local server; WebGL 2 is required.`;}

async function init(){
  [catalogue,compositions,physics,optics]=await Promise.all([
    fetch('catalogue/elements.json').then(r=>r.json()),fetch('catalogue/compositions.json').then(r=>r.ok?r.json():[]).catch(()=>[]),
    import('./physics/index.js').catch(e=>{console.warn('Numerical physics unavailable',e);return null;}),
    import('./optics.js').catch(()=>null)
  ]);
  if(!Array.isArray(catalogue))catalogue=catalogue.elements||[];
  if(!Array.isArray(compositions))compositions=compositions.compositions||[];
  scene=new THREE.Scene();scene.background=new THREE.Color(palette[state.theme][0]);scene.fog=new THREE.FogExp2(palette[state.theme][0],.025);
  renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
  renderer.setPixelRatio(qaMode?.3:Math.min(window.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.78;renderer.outputColorSpace=THREE.SRGBColorSpace;
  $('#viewport').appendChild(renderer.domElement);
  camera=new THREE.PerspectiveCamera(37,1,.05,180);camera.position.set(8.7,6.9,14.5);
  controls=new OrbitControls(camera,renderer.domElement);controls.target.set(1.7,1.65,0);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=2.2;controls.maxDistance=34;controls.maxPolarAngle=Math.PI*.51;controls.autoRotateSpeed=.35;controls.enablePan=true;
  const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();environmentPMREM=pmrem.fromScene(room,.035);scene.environment=environmentPMREM.texture;scene.environmentIntensity=.42;room.dispose();pmrem.dispose();
  materials=createMaterials(state.theme);buildLights();buildEnvironment();content=new THREE.Group();scene.add(content);
  composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));bloomPass=new UnrealBloomPass(new THREE.Vector2(1,1),.3,.7,1.05);composer.addPass(bloomPass);composer.addPass(new OutputPass());
  buildCatalogue();buildCompositions();buildWorld();bindUI();bindPointer();resizeObserver=new ResizeObserver(resize);resizeObserver.observe($('#viewport'));resize();
  if(matchMedia('(prefers-reduced-motion: reduce)').matches){state.motion=false;$('#motion').checked=false;}
  if(qaMode)await backdropReady;
  window.OPALINE={state,scene,camera,renderer,controls,bus,catalogue,compositions,select:selectElement,mode:setMode,theme:setTheme,frame:()=>renderFrame(1/60),render:()=>renderFrame(0),get selection(){return selectedObject;},get physics(){return state.simulation;},screenshot:exportPNG,exportGLB,getStats:()=>({...renderer.info.render,fps:state.fps})};
  $('#loading').classList.add('done');if(qaMode){state.motion=false;$('#motion').checked=false;renderFrame(1/60);}else renderer.setAnimationLoop(loop);
}

function buildLights(){
  scene.add(new THREE.HemisphereLight(0xc5eadc,0x142640,.55));
  const sun=new THREE.DirectionalLight(0xe4f3ff,1.8);sun.position.set(-5,9,7);sun.castShadow=true;sun.shadow.mapSize.set(qaMode?512:2048,qaMode?512:2048);sun.shadow.camera.left=-11;sun.shadow.camera.right=11;sun.shadow.camera.top=11;sun.shadow.camera.bottom=-11;sun.shadow.camera.near=.5;sun.shadow.camera.far=35;sun.shadow.normalBias=.025;sun.shadow.bias=-.00008;sun.shadow.radius=4;scene.add(sun);
  const rim=new THREE.DirectionalLight(0x6bbaff,1.25);rim.position.set(8,5,-6);scene.add(rim);
  const coral=new THREE.PointLight(0x8ebdff,8,15,2);coral.position.set(3,4,3);scene.add(coral);
  const under=new THREE.PointLight(0x80ceff,6,12,2);under.position.set(-2,.4,1);scene.add(under);
}

function buildEnvironment(){
  if(environment){scene.remove(environment);disposeGeometries(environment);}environment=new THREE.Group();environment.name='Abstract liquid mineral realm';scene.add(environment);
  const floorMat=new THREE.MeshPhysicalMaterial({color:state.theme==='tidal'?0x102f50:palette[state.theme][0],roughness:.25,metalness:.16,clearcoat:1,clearcoatRoughness:.12});
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(120,120),floorMat);floor.rotation.x=-Math.PI/2;floor.position.y=-.62;floor.receiveShadow=true;environment.add(floor);
  const waterGeo=new THREE.PlaneGeometry(70,70,180,180);waterGeo.rotateX(-Math.PI/2);water=new THREE.Mesh(waterGeo,materials.water);water.position.y=-.12;water.receiveShadow=true;water.name='Shared optical water surface';water.userData.rest=waterGeo.attributes.position.array.slice();environment.add(water);
  // Sculpted continuous mineral shelves, deliberately abstract and architectural.
  const shelfMat=materials.stone;const mirror=new Reflector(new THREE.PlaneGeometry(70,70),{color:0x496c8e,textureWidth:qaMode?128:1536,textureHeight:qaMode?128:1536,clipBias:.003,multisample:qaMode?0:4});mirror.rotation.x=-Math.PI/2;mirror.position.y=-.2;mirror.name='Planar water reflection';const reflectPass=mirror.onBeforeRender.bind(mirror);let lastReflection=-1,reflecting=false;mirror.onBeforeRender=(...args)=>{if(reflecting||lastReflection===reflectionSerial)return;reflecting=true;lastReflection=reflectionSerial;try{reflectPass(...args);}finally{reflecting=false;}};environment.add(mirror);
  for(let i=0;i<3;i++){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,64,40),shelfMat);mesh.position.set((i%2?1:-1)*(13+i*2.4),-.2+i*.13,-9-i*3.2);mesh.scale.set(5+i*.48,.7+i*.11,3+i*.24);mesh.rotation.y=i*.58;mesh.castShadow=true;mesh.receiveShadow=true;environment.add(mesh);}
  // Distinct depth layers: far hovering mineral islands and foreground rounded stones.
  for(let i=0;i<16;i++){const mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1,4),i%3===0?materials.nacre:materials.stone);const a=i*2.39996,r=6.5+i*.52;mesh.position.set(Math.cos(a)*r,-.04+Math.sin(i)*.1,Math.sin(a)*r-3);mesh.scale.set(.45+(i%4)*.17,.18+(i%3)*.07,.37+(i%5)*.11);mesh.rotation.set(i*.34,i*.22,i*.12);mesh.castShadow=true;mesh.receiveShadow=true;environment.add(mesh);}
  const glowGeo=new THREE.SphereGeometry(.025,10,8);for(let i=0;i<52;i++){const g=new THREE.Mesh(glowGeo,materials.glow);g.position.set(Math.sin(i*33.12)*10,.2+(i%11)*.24,Math.cos(i*15.41)*8-2);g.userData.home=g.position.clone();g.userData.phase=i;environment.add(g);}
  const backdropMat=new THREE.MeshBasicMaterial({color:0x84a6c4,fog:true,depthWrite:false});backdrop=new THREE.Mesh(new THREE.PlaneGeometry(72,40),backdropMat);backdrop.position.set(-8,12,-40);backdrop.rotation.y=.15;backdrop.visible=false;environment.add(backdrop);backdropReady=loadBackdrop();
  const fogMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{uColor:{value:new THREE.Color(palette[state.theme][1])}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 vP;uniform vec3 uColor;void main(){float a=pow(max(0.,1.-length(vP.xy)),3.)*.08;gl_FragColor=vec4(uColor,a);}' });
  for(let i=0;i<6;i++){const mist=new THREE.Mesh(new THREE.PlaneGeometry(2,2),fogMat);mist.position.set(Math.sin(i)*10,1.2,-5-i*4);mist.scale.set(17,3,1);environment.add(mist);}
}

async function loadBackdrop(){const targetBackdrop=backdrop,targetTheme=state.theme;const name={tidal:'tidal',opal:'opal',moss:'moss',obsidian:'obsidian',aurora:'aurora',amber:'amber'}[state.theme];const path=`assets/artwork/background-${name}.png`;try{const res=await fetch(path,{method:'HEAD'});if(!res.ok)return;const tex=await new THREE.TextureLoader().loadAsync(path);tex.colorSpace=THREE.SRGBColorSpace;if(backdrop!==targetBackdrop||state.theme!==targetTheme){tex.dispose();return;}if(backdrop.material.map)backdrop.material.map.dispose();backdrop.material.map=tex;backdrop.material.color.set(0x7899b8);backdrop.material.needsUpdate=true;backdrop.visible=true;}catch(e){/* The geometric abstract environment is complete without a backplate. */}}

function disposeGeometries(group){const shared=new Set(Object.values(materials||{})),geometries=new Set(),ownedMaterials=new Set(),textures=new Set();group.traverse(o=>{if(o.isReflector)o.getRenderTarget().dispose();if(o.geometry)geometries.add(o.geometry);for(const mat of(Array.isArray(o.material)?o.material:o.material?[o.material]:[])){if(!shared.has(mat)){ownedMaterials.add(mat);if(mat.map)textures.add(mat.map);}}});geometries.forEach(g=>g.dispose());ownedMaterials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());}
function clearContent(){releasePointer();transitionSystem?.dispose();transitionSystem=null;transitionHandle=null;transitionId=null;if(caustics){caustics.dispose?.();caustics=null;}motions.forEach(m=>m.dispose());motions.length=0;animated.length=0;pickables.length=0;state.simulation?.dispose?.();state.simulation=null;disposeGeometries(content);content.clear();selectedObject=null;}

function addElement(id,position=[0,0,0],scale=1,rotation=[0,0,0],options={}){
  const instanceMaterials=options.material&&materials[options.material]?{...materials,gel:materials[options.material]}:materials;const group=createElement(id,instanceMaterials,options);group.position.fromArray(position);group.rotation.fromArray(rotation);if(Array.isArray(scale))group.scale.multiply(new THREE.Vector3(...scale));else group.scale.multiplyScalar(scale);group.userData.elementId=id;
  group.traverse(mesh=>{if(mesh.isMesh){mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.elementRoot=group;pickables.push(mesh);}});content.add(group);const motion=new MotionController(group,{id,onChange:v=>{$('#interaction-state').textContent=`VALUE ${Math.round(v*100)}%`;bus.emit('change',group.position,1,{value:v});}});motions.push(motion);group.userData.motionController=motion;return group;
}

function buildWorld(){
  clearContent();state.mode='world';updateModeUI();
  // A complete text-free interface assembly lives in one three-dimensional world.
  const panel=addElement('C03',[3.45,2.85,-.55],[1.65,1.45,1],[-.16,-.17,.03]);
  const surface=addElement('C01',[3.0,1.8,.2],[1.3,.95,.85],[-.18,-.15,.02]);
  const heroGel=addElement('N01',[2.6,3.64,.25],.9,[-.06,-.2,-.1],{material:'blue'});const heroVolumeMaterial=createVolumeMaterial({shape:'ellipsoid',bounds:[.48,.70,.22],density:.72,color:'#8bbbec',lightPosition:[-2,4,2]});const heroVolume=new THREE.Mesh(new THREE.BoxGeometry(.96,1.4,.44),heroVolumeMaterial);heroVolumeMaterial.userData.bindVolume(heroVolume);heroGel.add(heroVolume);state.seed=heroGel;heroGel.userData.impulse=()=>{state.seedStart=state.time;};addSeedSequence(heroGel);animated.push({type:'custom',update:()=>{heroVolumeMaterial.uniforms.uTime.value=state.time;}});
  addElement('B13',[4.35,3.33,.65],.56,[.03,-.22,0]);
  addElement('B01',[3.2,2.56,1.0],1.03,[-.1,-.15,.02]);
  addElement('B09',[4.6,1.66,1.2],.67,[-.11,-.15,.03]);
  addElement('A09',[1.48,2.3,1.12],.57,[.1,-.1,-.1]);
  addElement('A22',[2.28,1.32,1.25],.53,[-.12,-.08,.05]);
  addElement('A08',[3.4,1.22,1.35],.57,[.15,-.08,.18]);
  addElement('D01',[3.45,.61,1.5],[1.55,.75,1.1],[-.25,-.18,0]);
  const bubble=addElement('F01',[5.88,4.14,-.18],.52);animated.push({type:'float',object:bubble,home:bubble.position.clone(),phase:.3});
  const bubble2=addElement('F02',[1.3,4.25,-1],.35);animated.push({type:'float',object:bubble2,home:bubble2.position.clone(),phase:2});
  const drop=addElement('E09',[5.6,1.45,1.35],.64);animated.push({type:'float',object:drop,home:drop.position.clone(),phase:3});buildFluidSpecimen(drop,{position:[3.25,.12,1.75],scale:[1.9,.6,1.5]});
  addElement('N05',[.35,.7,2.2],.55,[.2,.1,-.65]);selectedObject=panel;frameScene({position:[8,5.4,13.3],target:[2.8,2.1,0]},false);
  $('#scene-title').innerHTML='A softer kind<br>of interface.';$('#scene-subtitle').textContent='Sculpted in gel. Suspended in light.';$('#selected-code').textContent='OPALINE / MATERIAL WORLD';$('#selected-name').textContent='Connected by nature';$('#selected-description').textContent='Touch a body to compress it. Pull a slider. Turn a dial. Drag the open water to explore the perspective.';$('#material-label').textContent='PHYSICAL TRANSMISSION';$('#scene-tag').textContent='SCULPTED GEL · ABSTRACT LIQUID REALM';
}

function addSeedSequence(seed){
  const orbit=new THREE.Group();orbit.name='Twelve lens radial reveal';content.add(orbit);const lenses=[];for(let i=0;i<12;i++){const g=createElement('A03',materials);g.scale.set(.19,.19,.24);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});orbit.add(g);lenses.push(g);}
  const light=new THREE.PointLight(0x75c3ff,0,6,1.5);content.add(light);const home=seed.position.clone();const threads=[];for(let i=0;i<5;i++){const a=i/5*Math.PI*2;const pts=[];for(let j=0;j<20;j++){const f=j/19,r=f*2;pts.push(new THREE.Vector3(home.x+Math.cos(a+f*.8)*r,.035+Math.sin(f*Math.PI)*.05,home.z+Math.sin(a+f*.8)*r));}const geo=new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),48,.009,6,false),mat=new THREE.MeshBasicMaterial({color:0x8dcaff,transparent:true,opacity:0});const m=new THREE.Mesh(geo,mat);content.add(m);threads.push(m);}
  animated.push({type:'custom',update:()=>{const t=state.time-state.seedStart,active=t>=0&&t<10,wake=t<2?clamp((t-.75)/1.25,0,1):Math.exp(-Math.max(0,t-4)*.55),rise=t<4.2?clamp((t-3)/1.2,0,1):1-clamp((t-4.2)/1.8,0,1),reveal=t<4.2?clamp((t-3)/1.2,0,1):1-clamp((t-5.3)/1.2,0,1);const smooth=rise*rise*(3-2*rise);seed.position.y=home.y+(active?smooth*.7:0);light.position.copy(seed.position).add(new THREE.Vector3(0,0,.5));light.intensity=active?wake*10:0;heroExcitation(seed,active?wake:0);orbit.visible=active&&reveal>.001;for(let i=0;i<12;i++){const a=i/12*Math.PI*2+t*.15;const radius=1.15*reveal;lenses[i].position.set(home.x+Math.cos(a)*radius,home.y+smooth*.7+Math.sin(a)*radius*.6,home.z+Math.sin(a)*radius*.55);lenses[i].scale.setScalar(.17*reveal);lenses[i].rotation.y=Math.sin(a)*.4;}for(let i=0;i<threads.length;i++)threads[i].material.opacity=active?clamp((t-2)*2,0,1)*Math.exp(-Math.max(0,t-3)*.7)*.5:0;}});
}
function heroExcitation(root,strength){root.traverse(o=>{if(o.material?.uniforms?.uExcitation)o.material.uniforms.uExcitation.value=strength;if(o.material?.userData?.opaline?.uniforms?.uOpExcitation)o.material.userData.opaline.uniforms.uOpExcitation.value=strength;});}

function selectElement(id){const entry=catalogue.find(e=>e.id===id);if(!entry)return;state.selected=id;state.mode='specimen';clearContent();updateModeUI();const family=id[0];let root;
  if('ABCDEFJN'.includes(family)){root=addElement(id,[1.6,1.85,0],1.4);selectedObject=root;if(family==='E'&&[1,2,3,4,5,6,7,10,21,24].includes(+id.slice(1)))buildFluidSpecimen(root);if(id==='F07'&&physics?.Cloth){hideAuthoredSpecimen(root);root=buildClothSpecimen();}if(['F01','F02','F03','F04','F05','F08','F09'].includes(id)&&physics?.BubbleFilm){hideAuthoredSpecimen(root);root=buildBubbleSpecimen(id);}if(family==='J'&&['J19','J20'].includes(id))addVolume(root,id==='J20');if(id==='J24'){for(let j=0;j<3;j++){const sample=new THREE.Mesh(new THREE.SphereGeometry(.55,40,28),[materials.gel,materials.blue,materials.nacre][j]);sample.position.set((j-1)*1.2,0,.3);root.add(sample);}}}
  else if(family==='G'||family==='H')root=buildParticleSpecimen(id);
  else if(family==='I')root=buildOpticalSpecimen(id);
  else if(family==='K')root=buildContactSpecimen(id);
  else if(family==='L')root=buildTransitionSpecimen(id);
  selectedObject=root||selectedObject;$('#scene-title').textContent=entry.name;$('#scene-subtitle').textContent=entry.description||entry.geometry_or_domain||'';$('#selected-code').textContent=`${entry.id} / ${entry.familyName||fallbackNames[family]}`;$('#selected-name').textContent=entry.name;$('#selected-description').textContent=entry.implementation?.summary||entry.behavior||'A reusable physical element from the Opaline material world.';$('#selected-description').title=(entry.implementation?.limitations||[]).join(' · ');if(entry.implementation?.limitations?.length)$('#selected-description').textContent+=' '+entry.implementation.limitations[0];$('#material-label').textContent=family==='G'||family==='H'?'3D PARTICLE DYNAMICS':family==='K'?'XPBD CONTACT SPECIMEN':family==='I'?'PHYSICAL OPTICS':family==='L'?'COORDINATED SPATIAL MOTION':'VOLUMETRIC GEOMETRY';$('#interaction-state').textContent='READY TO TOUCH';
  if(entry.implementation?.status?.includes('gap'))$('#material-label').textContent='REFERENCE STUDY / PARTIAL';frameObject(root);buildList();document.body.classList.remove('mobile-library');return root;
}

function frameObject(root){if(!root)return;const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const d=clamp(Math.max(size.x,size.y,size.z)*2.0,5.5,18);const target=center.clone();target.x-=d*.13;target.y-=d*.01;frameScene({position:target.clone().add(new THREE.Vector3(.54,.3,1).normalize().multiplyScalar(d)).toArray(),target:target.toArray()});}
function frameScene({position,target},animate=!qaMode){if(animate){cameraTween={start:camera.position.clone(),end:new THREE.Vector3(...position),from:controls.target.clone(),to:new THREE.Vector3(...target),time:0};}else{camera.position.fromArray(position);controls.target.fromArray(target);controls.update();}}

function buildParticleSpecimen(id){
  const root=new THREE.Group();root.position.set(1.8,1.65,0);root.name=`Particle field ${id}`;content.add(root);const n=+id.slice(1),isField=id[0]==='H';
  if(!physics?.createParticlePreset)return addElement('F05',[1.8,2,0],1);
  const collider=new physics.BoxCollider({min:[-2,-.95,-1.8],max:[2,2.2,1.8],inside:true,restitution:.65,friction:.1});
  const fields=isField?[physics.createFieldPreset(id)]:undefined;
  const system=physics.createParticlePreset(isField?'G01':id,{count:id==='G17'?30:isField?360:240,origin:[0,.4,0],colliders:[collider],fields,seed:42+n});
  const count=system.capacity,shape=system.metadata.shape;
  const particleGeometry=shape==='petal'?new THREE.SphereGeometry(1,12,8):new THREE.IcosahedronGeometry(1,2);
  const mesh=new THREE.InstancedMesh(particleGeometry,system.metadata.emission?materials.glow:system.metadata.transmission?materials.shell:materials.nacre,count);root.add(mesh);mesh.castShadow=true;mesh.count=system.count;mesh.boundingSphere=new THREE.Sphere(new THREE.Vector3(0,.6,0),4);
  let trails=null;if(system.trailLength){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(system.capacity*(system.trailLength-1)*6),3));trails=new THREE.LineSegments(geometry,new THREE.LineBasicMaterial({color:0x99d8f2,transparent:true,opacity:.22,depthWrite:false}));root.add(trails);}
  const world=new physics.PhysicsWorld({fixedDt:1/90,maxSubsteps:5});world.add(system);
  const sync=()=>{mesh.count=system.count;for(let i=0;i<system.count;i++){dummy.position.fromArray(system.positions,i*3);dummy.quaternion.fromArray(system.orientations,i*4);const r=system.radii[i]*1.55;dummy.scale.set(r,r,r);if(shape==='petal')dummy.scale.set(r*.6,r*1.8,r*.24);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,new THREE.Color().fromArray(system.colors,i*3));}mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;
    if(trails){const a=trails.geometry.attributes.position.array;let k=0;for(let i=0;i<system.count;i++)for(let j=0;j<system.trailLength-1;j++){const a1=((system.trailHead-j+system.trailLength)%system.trailLength*system.capacity+i)*3,a2=((system.trailHead-j-1+system.trailLength)%system.trailLength*system.capacity+i)*3;for(let q=0;q<3;q++)a[k++]=system.trails[a1+q];for(let q=0;q<3;q++)a[k++]=system.trails[a2+q];}trails.geometry.setDrawRange(0,k/3);trails.geometry.attributes.position.needsUpdate=true;}
  };sync();animated.push({type:'custom',update:dt=>{if(dt>0)world.step(dt);sync();}});
  root.userData.impulse=(point,strength)=>{const p=root.worldToLocal(point.clone());if(system.adhesionAcceleration>0)for(let i=0;i<system.count;i++){if(Math.hypot(system.positions[i*3]-p.x,system.positions[i*3+1]-p.y,system.positions[i*3+2]-p.z)<2.8)system.releaseParticle(i);}system.addImpulse(p.toArray(),2.8,[strength*.025,strength*.05,.015]);if(system.metadata.burst)system.burst(p.toArray(),[0,1,0],1.8,30);};pickables.push(mesh);mesh.userData.elementRoot=root;state.simulation={kind:'particle-field',system,world,positions:system.positions,velocity:system.velocities,count:system.count};return root;
}

function addVolume(root,corridor=false){const bounds=corridor?[2.6,.65,1]:[1.7,.85,1.2];const mat=createVolumeMaterial({shape:'box',bounds,density:.09,color:'#b8cfe8',lightPosition:[2,3,2]});const mesh=new THREE.Mesh(new THREE.BoxGeometry(...bounds.map(v=>v*2)),mat);mat.userData.bindVolume(mesh);mesh.position.y=.15;root.add(mesh);animated.push({type:'custom',update:()=>{if(mat.uniforms.uTime)mat.uniforms.uTime.value=state.time;}});return mesh;}
function buildOpticalSpecimen(id){const n=+id.slice(1);let root;
  if(n===2){root=new THREE.Group();root.position.set(1.9,2.65,0);root.name='Concave reflective caustic shell';const mirror=new THREE.Mesh(new THREE.SphereGeometry(1.05,56,36,0,Math.PI*2,0,Math.PI/2),new THREE.MeshPhysicalMaterial({color:0xbfdcec,metalness:1,roughness:.04,side:THREE.DoubleSide}));mirror.castShadow=true;root.add(mirror);content.add(root);mirror.userData.elementRoot=root;pickables.push(mirror);root.userData.impulse=()=>{root.rotation.z+=.08;};}
  else root=addElement(n===11?'F01':n===9?'A15':n===3?'E12':'A03',[1.9,n===4?3:2,0],1.75);
  if(n===5||n===13||n===14){const mat=createVolumeMaterial({shape:'ellipsoid',bounds:[.83,.6,.32],density:n===13?2.8:1.1,color:'#97c7ec',lightPosition:[1,2,1]});const volume=new THREE.Mesh(new THREE.BoxGeometry(1.66,1.2,.64),mat);mat.userData.bindVolume(volume);root.add(volume);animated.push({type:'custom',update:()=>{if(mat.uniforms.uTime)mat.uniforms.uTime.value=state.time;}});}
  const light=new THREE.PointLight(n%2?0xb6e6d9:0xe0badb,8+n,5,1.5);root.add(light);animated.push({type:'custom',update:()=>{light.position.set(Math.sin(state.time*.7)*.45,Math.cos(state.time*.5)*.4,.1);light.intensity=(7+n)*(.8+Math.sin(state.time*.6)*.18);}});
  if(n<=4&&optics?.RefractiveCaustics){const meshes=[];root.traverse(o=>{if(o.isMesh)meshes.push(o);});try{const receiver=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.MeshStandardMaterial({color:0x7097b9,roughness:.42}));receiver.rotation.x=-Math.PI/2;receiver.position.set(1.9,.1,0);content.add(receiver);const volume=n===4?{bounds:new THREE.Box3(new THREE.Vector3(-1.7,.12,-3),new THREE.Vector3(5.5,1.45,3)),resolution:[32,28,32],extinction:.18,albedo:.92,onlyCaustics:true}:null;
    caustics=new optics.RefractiveCaustics({refractors:n===2?[]:meshes,reflectors:n===2?meshes:[],receiver,resolution:128,photonsPerUpdate:qaMode?96:700,lightPosition:n===2?new THREE.Vector3(-2,1.6,2):n===4?new THREE.Vector3(-1,7,2):new THREE.Vector3(-3,6,4),lightTarget:n===2?new THREE.Vector3(1.9,2.8,0):n===4?new THREE.Vector3(1.9,3,0):new THREE.Vector3(1.9,1,0),aperture:new THREE.Vector2(3,3),transport:n===2?'reflection':n===4?'split':'transmission',volume});optics.attachCaustics?.(receiver.material,caustics.texture,1.8);
    if(n===4&&optics.createVolumeCausticsMaterial){const mat=optics.createVolumeCausticsMaterial(caustics,{steps:128,intensity:1.4,anisotropy:.35}),size=volume.bounds.getSize(new THREE.Vector3()),medium=new THREE.Mesh(new THREE.BoxGeometry(size.x,size.y,size.z),mat);medium.position.copy(volume.bounds.getCenter(new THREE.Vector3()));mat.userData.bindVolume(medium);content.add(medium);}
    root.updateWorldMatrix(true,true);caustics.update(state.time);
  }catch(e){console.warn('Caustic integration',e);}}
  return root;
}

function buildContactSpecimen(id){const n=+id.slice(1);if(n===13){const root=addElement('E03',[1.7,1.65,0],1.5);buildFluidSpecimen(root);return root;}if(n===14)return physics?.BubbleFilm?buildBubbleSpecimen('F03'):addElement('F03',[1.7,2,0],1.5);if(n===17)return buildParticleSpecimen('G15');if(n===18){const study=addElement('J06',[1.7,1,0],1.3);buildFluidSpecimen(study);return study;}
  if(!physics?.SoftBody||!physics?.makeTetGrid)return addElement('A01',[1.7,2,0],1.6);
  const grid=physics.makeTetGrid({nx:7,ny:5,nz:5,size:[2.1,1.4,1.1],origin:[.65,1.25,-.55],shape:'ellipsoid'});
  const contactRecipe=physics.createContactRecipe?.(id)||{};const colliders=physics.PlaneCollider?[new physics.PlaneCollider({offset:.35,restitution:contactRecipe.restitution??.1,friction:contactRecipe.friction??.3})]:[];
  const soft=new physics.SoftBody({...grid,edgeCompliance:1e-5,volumeCompliance:1e-8,damping:n===19?.65:1.8,iterations:10,colliders,gravity:n===19?[0,-3.2,0]:[0,-9.81,0],fields:n===19?[new physics.BuoyancyField({surfaceY:1.5,bodyDensity:650,gravity:3.2,thickness:.2})]:[]});
  // Keep the base mounted while allowing local volume-preserving contact deformation.
  let minY=Infinity;for(let i=1;i<grid.positions.length;i+=3)minY=Math.min(minY,grid.positions[i]);for(let i=0;i<grid.positions.length/3;i++)if(n!==15&&n!==16&&n!==19&&grid.positions[i*3+1]<minY+.12)soft.pin(i);
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(soft.positions,3));geo.setIndex(new THREE.BufferAttribute(grid.surfaceIndices,1));geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,materials.gel);mesh.castShadow=true;mesh.receiveShadow=true;const root=new THREE.Group();root.add(mesh);content.add(root);pickables.push(mesh);mesh.userData.elementRoot=root;
  const world=new physics.PhysicsWorld({fixedDt:1/120,maxSubsteps:8});world.add(soft);const contactDemo=physics.ContactController?new physics.ContactController(soft,id,{loop:true}):null;state.simulation={kind:'xpbd',soft,world,mesh,root,contactDemo};animated.push({type:'custom',update:dt=>{if(dt>0){contactDemo?.update(dt);world.step(dt);}geo.attributes.position.needsUpdate=true;geo.computeVertexNormals();geo.computeBoundingSphere();}});
  root.userData.grab=(point)=>{contactDemo?.cancel();const order=[];for(let i=0;i<soft.positions.length/3;i++){const d=(soft.positions[i*3]-point.x)**2+(soft.positions[i*3+1]-point.y)**2+(soft.positions[i*3+2]-point.z)**2;order.push([d,i]);}order.sort((a,b)=>a[0]-b[0]);soft.grab('pointer',order.slice(0,6).map(p=>p[1]),point.toArray(),1e-7);};root.userData.moveGrab=p=>soft.moveGrab('pointer',p.toArray());root.userData.releaseGrab=()=>soft.releaseGrab('pointer');
  if(n===10||n===22){const otherGrid=physics.makeTetGrid({nx:6,ny:4,nz:4,size:[1.6,1.2,1.1],origin:[2.4,1.25,-.55],shape:'ellipsoid'}),other=new physics.SoftBody({...otherGrid,edgeCompliance:1e-5,volumeCompliance:1e-8,damping:1,iterations:8,colliders});for(let i=0;i<other.count;i++)other.velocities[i*3]=-.6;world.add(other);world.couple(soft,other,{radiusA:.085,radiusB:.085,restitution:.2});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(other.positions,3));g.setIndex(new THREE.BufferAttribute(otherGrid.surfaceIndices,1));g.computeVertexNormals();const m=new THREE.Mesh(g,materials.blue);m.castShadow=true;root.add(m);animated.push({type:'custom',update:()=>{g.attributes.position.needsUpdate=true;g.computeVertexNormals();g.computeBoundingSphere();}});}
  if(n===12){const particles=physics.createParticlePreset('G09',{count:70,origin:[.65,3,-.55],fields:[],colliders});for(let i=0;i<particles.count;i++){particles.velocities[i*3]=0;particles.velocities[i*3+1]=-1.7;particles.velocities[i*3+2]=0;}world.add(particles);world.couple(particles,soft,{radiusB:.09,restitution:.3});const droplets=new THREE.InstancedMesh(new THREE.SphereGeometry(1,10,8),materials.glow,particles.capacity);root.add(droplets);droplets.boundingSphere=new THREE.Sphere(new THREE.Vector3(1.7,2,0),5);animated.push({type:'custom',update:()=>{droplets.count=particles.count;for(let i=0;i<particles.count;i++){dummy.position.fromArray(particles.positions,i*3);dummy.scale.setScalar(particles.radii[i]*1.8);dummy.quaternion.identity();dummy.updateMatrix();droplets.setMatrixAt(i,dummy.matrix);}droplets.instanceMatrix.needsUpdate=true;}});}
  if(n===19){const region=new THREE.Mesh(new THREE.PlaneGeometry(4,3.1),materials.water);region.rotation.x=-Math.PI/2;region.position.set(.65,1.5,-.55);root.add(region);for(let i=0;i<soft.count;i++){soft.velocities[i*3]=.15;soft.velocities[i*3+2]=(soft.positions[i*3]-.65)*.12;}}
  if(n===11||n===16)addElement('J06',[.65,.22,-.55],[1.4,.3,.8]);return root;
}

function hideAuthoredSpecimen(root){root.visible=false;for(let i=pickables.length-1;i>=0;i--)if(pickables[i].userData.elementRoot===root)pickables.splice(i,1);}
function buildBubbleSpecimen(id){
  const n=+id.slice(1),count=n===3?2:n===4?3:n===5?5:1,root=new THREE.Group();root.name='Gas-volume constrained film';content.add(root);const world=new physics.PhysicsWorld({fixedDt:1/120,maxSubsteps:6}),bubbles=[],meshes=[];
  for(let j=0;j<count;j++){const centers=count===1?[1.7,2,0]:count===2?[1.7+(j-.5)*1.04,2,0]:[1.7+Math.cos(j/count*Math.PI*2)*.8,2+Math.sin(j/count*Math.PI*2)*.65,j%2*.12];const grid=physics.makeBubbleMesh({subdivisions:3,radius:count>3?.53:.66,center:centers});if(n===2){for(let i=0;i<grid.positions.length;i+=3){grid.positions[i]=centers[0]+(grid.positions[i]-centers[0])*.85;grid.positions[i+1]=centers[1]+(grid.positions[i+1]-centers[1])*1.38;grid.positions[i+2]=centers[2]+(grid.positions[i+2]-centers[2])*.85;}}
    const bubble=new physics.BubbleFilm({...grid,thickness:(300+j*60)*1e-9,gasCompliance:1e-8,edgeCompliance:8e-4,drainageTimeScale:n===8||n===9?1e5:1});world.add(bubble);bubbles.push(bubble);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(bubble.positions,3));geo.setAttribute('filmThickness',new THREE.BufferAttribute(bubble.thickness,1));geo.setIndex(new THREE.BufferAttribute(bubble.triangles,1));geo.computeVertexNormals();const mat=MaterialLibrary.cloneMaterial(materials.film);MaterialLibrary.enableFilmThickness?.(mat);const mesh=new THREE.Mesh(geo,mat);mesh.castShadow=true;mesh.receiveShadow=true;root.add(mesh);meshes.push(mesh);pickables.push(mesh);mesh.userData.elementRoot=root;
  }
  for(let a=0;a<count;a++)for(let b=a+1;b<count;b++)world.couplings.push(new physics.BubblePairCoupling(bubbles[a],bubbles[b],{gap:.002,iterations:8}));
  animated.push({type:'custom',update:dt=>{if(dt>0)world.step(dt);meshes.forEach(m=>{m.geometry.attributes.position.needsUpdate=true;m.geometry.attributes.filmThickness.needsUpdate=true;m.geometry.computeVertexNormals();m.geometry.computeBoundingSphere();MaterialLibrary.updateMaterials([m.material],state.time);});}});
  let active=null;root.userData.grab=point=>{const nearest=[];for(const bubble of bubbles)for(let i=0;i<bubble.count;i++)nearest.push({bubble,i,d:(bubble.positions[i*3]-point.x)**2+(bubble.positions[i*3+1]-point.y)**2+(bubble.positions[i*3+2]-point.z)**2});nearest.sort((a,b)=>a.d-b.d);active=nearest[0].bubble;active.grab('pointer',nearest.filter(x=>x.bubble===active).slice(0,6).map(x=>x.i),point.toArray(),1e-7);};root.userData.moveGrab=p=>active?.moveGrab('pointer',p.toArray());root.userData.releaseGrab=()=>{active?.releaseGrab('pointer');active=null;};state.simulation={kind:'bubble-film',bubbles,world,meshes,acceleratedDrainage:n===8||n===9};return root;
}

function buildClothSpecimen(){
  const grid=physics.makeClothGrid({nx:24,ny:20,size:[2.3,1.8],origin:[1.7,2,0],plane:'xy'});const cloth=new physics.Cloth({...grid,gravity:[0,-.9,0],inverseMass:6,stretchCompliance:1e-7,bendCompliance:5e-4,damping:.7,aerodynamicWind:[.3,0,1.4],iterations:8});for(let i=0;i<cloth.count;i++)if(cloth.positions[i*3+1]>2.88&&(cloth.positions[i*3]<.62||cloth.positions[i*3]>2.78))cloth.pin(i);
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(cloth.positions,3));geo.setIndex(new THREE.BufferAttribute(grid.triangles,1));geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,materials.film);mesh.castShadow=true;mesh.receiveShadow=true;const root=new THREE.Group();root.add(mesh);content.add(root);pickables.push(mesh);mesh.userData.elementRoot=root;const world=new physics.PhysicsWorld({fixedDt:1/120,maxSubsteps:6});world.add(cloth);animated.push({type:'custom',update:dt=>{cloth.aerodynamicWind[2]=1.1+Math.sin(state.time*.9)*.6;if(dt>0)world.step(dt);geo.attributes.position.needsUpdate=true;geo.computeVertexNormals();geo.computeBoundingSphere();}});
  root.userData.grab=p=>{const nearest=[];for(let i=0;i<cloth.count;i++)nearest.push([(cloth.positions[i*3]-p.x)**2+(cloth.positions[i*3+1]-p.y)**2+(cloth.positions[i*3+2]-p.z)**2,i]);nearest.sort((a,b)=>a[0]-b[0]);cloth.grab('pointer',nearest.slice(0,4).map(a=>a[1]),p.toArray(),1e-7);};root.userData.moveGrab=p=>cloth.moveGrab('pointer',p.toArray());root.userData.releaseGrab=()=>cloth.releaseGrab('pointer');state.simulation={kind:'xpbd-cloth',cloth,world};return root;
}

function buildFluidSpecimen(container,config={}){if(!physics?.PBFFluid)return;try{const positions=[];const spacing=.17;for(let y=0;y<5;y++)for(let z=0;z<8;z++)for(let x=0;x<11;x++)positions.push((x-5)*spacing+.15,(y*.17)+.35,(z-3.5)*spacing);const fluid=new physics.PBFFluid({positions:new Float32Array(positions),particleRadius:.065,smoothingRadius:.29,bounds:{min:[-1,-.1,-.85],max:[1.3,1.5,.85]},iterations:4,gravity:[0,-3.2,0]});
  const surface=new MarchingCubes(28,materials.water,true,true,100000);surface.position.fromArray(config.position||[1.7,1.5,0]);surface.scale.fromArray(config.scale||[1.55,1.55,1.55]);surface.isolation=36;surface.castShadow=true;content.add(surface);pickables.push(surface);surface.userData.elementRoot=container;const world=new physics.PhysicsWorld({fixedDt:1/90,maxSubsteps:5});world.add(fluid);state.simulation={kind:'pbf',fluid,world,surface};animated.push({type:'custom',update:dt=>{if(dt>0)world.step(dt);surface.reset();for(let i=0;i<fluid.count*3;i+=3){surface.addBall(fluid.positions[i]/3.1+.5,fluid.positions[i+1]/3.1+.5,fluid.positions[i+2]/3.1+.5,.045,10);}surface.update();}});container.userData.impulse=(p,strength)=>{const q=surface.worldToLocal(p.clone()).multiplyScalar(3.1/2);fluid.addImpulse(q.toArray(),1.8,[strength*1.4,strength*3,.5]);};}catch(e){console.warn('Fluid reconstruction unavailable',e);}}

function buildTransitionSpecimen(id){const n=+id.slice(1),root=new THREE.Group();root.position.set(1.8,2,0);content.add(root);const parts=[];for(let i=0;i<(n===9||n===10?5:n===16||n===17?14:3);i++){const g=createElement(n===7||n===8?'E16':n===15?'F06':i===0?'C01':'A08',materials);root.add(g);g.scale.setScalar(i===0?1:.35);parts.push(g);g.traverse(o=>{if(o.isMesh){o.castShadow=true;pickables.push(o);o.userData.elementRoot=root;}});}
  const poses=parts.map((g,i)=>{g.position.set((i-(parts.length-1)/2)*.7,0,i*.04);if(parts.length>8)g.scale.setScalar(.14);return {position:g.position.clone(),rotation:g.rotation.clone(),scale:g.scale.clone()};});
  transitionSystem=new TransitionSystem({scene:content,camera,eventBus:bus});transitionId=id;let started=false;
  const run=()=>{if(transitionHandle?.status==='running')transitionSystem.cancel(transitionHandle);parts.forEach((g,i)=>{g.position.copy(poses[i].position);g.rotation.copy(poses[i].rotation);g.scale.copy(poses[i].scale);});const opts={object:root,objects:parts,duration:3.4};if(id==='L18'){opts.object=camera;opts.to=[5,2.5,6];opts.lookAt=[1.8,2,0];}transitionHandle=transitionSystem.play(id,opts);started=true;};root.userData.impulse=run;animated.push({type:'custom',update:()=>{if(!started&&!cameraTween)run();}});return root;
}

function buildComposition(index=0){const recipe=compositions[index];if(!recipe){buildWorld();toast('Composition catalogue not available.');return;}clearContent();state.mode='composition';updateModeUI();const assembly=new THREE.Group();assembly.name=recipe.name||recipe.title||recipe.id;content.add(assembly);
  for(const part of recipe.parts||[]){try{const g=addElement(part.element||part.elementId||part.id,[0,0,0],1,[0,0,0],{material:part.material});if(part.dimensions){const size=new THREE.Box3().setFromObject(g).getSize(new THREE.Vector3());g.scale.multiply(new THREE.Vector3(...part.dimensions.map((d,i)=>d/Math.max(size.getComponent(i),.01))));}if(part.scale){if(Array.isArray(part.scale))g.scale.multiply(new THREE.Vector3(...part.scale));else g.scale.multiplyScalar(part.scale);}g.position.fromArray(part.position||[0,0,0]);g.rotation.fromArray(part.rotation||[0,0,0]);assembly.attach(g);g.userData.motionController.initialPosition.copy(g.position);g.userData.partId=part.id;}catch(e){console.warn('Composition part',part,e);}}
  assembly.position.set(1.8,1.8,0);selectedObject=assembly;$('#scene-title').textContent=assembly.name;$('#scene-subtitle').textContent='Text-free components. One shared material language.';$('#selected-code').textContent=`ASSEMBLY / ${recipe.id||index+1}`;$('#selected-name').textContent=assembly.name;$('#selected-description').textContent=recipe.description||'Reusable spatial assembly. Content frames and semantic application bindings are declared in the composition recipe.';$('#material-label').textContent='SPATIAL COMPOSITION';frameObject(assembly);
}

function buildCatalogue(){const families=[...new Set(catalogue.map(e=>e.familyCode||e.family))];$('#element-count').textContent=catalogue.length;$('#families').innerHTML='';for(const f of ['all',...families]){const b=document.createElement('button');b.textContent=f==='all'?'All':fallbackNames[f]||f;b.dataset.family=f;b.classList.toggle('active',f===state.family);b.addEventListener('click',()=>{state.family=f;$('#families').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));buildList();});$('#families').append(b);}buildList();}
function buildList(){const q=state.search.toLowerCase(),items=catalogue.filter(e=>(state.family==='all'||(e.familyCode||e.family)===state.family)&&`${e.id} ${e.name} ${e.familyName} ${e.description}`.toLowerCase().includes(q));$('#elements').replaceChildren();$('#list-count').textContent=items.length;$('#list-label').textContent=state.family==='all'?'ALL ELEMENTS':(fallbackNames[state.family]||state.family).toUpperCase();for(const e of items){const b=document.createElement('button');b.className='element'+(state.selected===e.id&&state.mode==='specimen'?' active':'');b.dataset.family=e.id[0];b.dataset.id=e.id;b.setAttribute('role','listitem');const sw=document.createElement('span');sw.className='swatch';const label=document.createElement('span');label.className='element-name';label.textContent=e.name;const code=document.createElement('span');code.className='element-code';code.textContent=`${e.id} / ${e.familyName||fallbackNames[e.id[0]]}`;label.append(code);b.append(sw,label);b.addEventListener('click',()=>selectElement(e.id));$('#elements').append(b);}}
function buildCompositions(){const s=$('#composition');for(let i=0;i<compositions.length;i++){const o=document.createElement('option');o.value=i;o.textContent=compositions[i].name||compositions[i].title||compositions[i].id;s.append(o);}}
function updateModeUI(){document.body.classList.toggle('specimen',state.mode!=='world');document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#composition-picker').hidden=state.mode!=='composition';}
function setMode(mode){if(mode==='world')buildWorld();else if(mode==='composition')buildComposition(+$('#composition').value||0);else selectElement(state.selected);}
function setTheme(theme){state.theme=theme;const old=materials;materials=createMaterials(theme);scene.background.set(palette[theme][0]);scene.fog.color.set(palette[theme][0]);buildEnvironment();setMode(state.mode);Object.values(old).forEach(m=>m.dispose?.());return theme;}

function bindUI(){
  $('#seed-demo').addEventListener('click',()=>{if(state.mode!=='world')buildWorld();state.seedStart=state.time;toast('Contact → internal glow → lift → orbit → settle');});
  $('#search').addEventListener('input',e=>{state.search=e.target.value;buildList();});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('#composition').addEventListener('change',e=>buildComposition(+e.target.value));
  $('#theme').addEventListener('change',e=>setTheme(e.target.value));$('#quality').addEventListener('change',e=>{state.quality=e.target.value;renderer.setPixelRatio(state.quality==='ultra'?2:state.quality==='native'?1:Math.min(devicePixelRatio||1,1.5));resize();toast(state.quality==='ultra'?'Ultra rendering · 2× supersampling':'Render quality updated');});$('#motion').addEventListener('change',e=>{state.motion=e.target.checked;});$('#bloom').addEventListener('change',e=>{state.bloom=e.target.checked;bloomPass.enabled=state.bloom;});$('#autorotate').addEventListener('change',e=>controls.autoRotate=e.target.checked);
  for(const [id,direction] of [['camera-front',[0,.06,1]],['camera-three',[.55,.3,1]],['camera-side',[1,.12,.02]],['camera-top',[.01,1,.01]]]){$('#'+id).addEventListener('click',()=>{const d=camera.position.distanceTo(controls.target);frameScene({position:controls.target.clone().add(new THREE.Vector3(...direction).normalize().multiplyScalar(d)).toArray(),target:controls.target.toArray()});$('.controls-row').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.id===id));});}
  $('#reset').addEventListener('click',()=>{motions.forEach(m=>m.reset());if(state.mode==='world')frameScene({position:[8,5.4,13.3],target:[2.8,2.1,0]});else frameObject(selectedObject);toast('Camera and interaction reset');});$('#screenshot').addEventListener('click',exportPNG);$('#export-glb').addEventListener('click',exportGLB);$('#toggle-library').addEventListener('click',()=>{if(innerWidth<=720)document.body.classList.toggle('mobile-library');else document.body.classList.toggle('panel-hidden');});
  window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='Escape')releasePointer();if(e.key===' '){e.preventDefault();$('#motion').checked=state.motion=!state.motion;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){const m=selectedObject?.userData.motionController;if(m){e.preventDefault();m.setValue(m.value.target+((e.key==='ArrowRight'||e.key==='ArrowUp')?.05:-.05));}}});window.addEventListener('blur',releasePointer);document.addEventListener('visibilitychange',()=>{if(document.hidden)releasePointer();});
}

function pointerRay(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);}
function bindPointer(){const canvas=renderer.domElement;
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0||state.drag)return;pointerRay(e);const hits=raycaster.intersectObjects(pickables,false);if(!hits.length)return;const hit=hits[0],root=hit.object.userData.elementRoot;if(!root)return;const normal=camera.getWorldDirection(new THREE.Vector3()),plane=new THREE.Plane().setFromNormalAndCoplanarPoint(normal,hit.point);state.drag={id:e.pointerId,root,plane,point:hit.point.clone(),startPoint:hit.point.clone(),lastX:e.clientX,lastY:e.clientY};controls.enabled=false;cameraTween=null;canvas.setPointerCapture(e.pointerId);root.userData.motionController?.begin(hit.point,hit.object);root.userData.grab?.(hit.point);root.userData.impulse?.(hit.point,1.2);bus.emit('touch',hit.point,1);$('#interaction-state').textContent='CONTACT / ACTIVE';canvas.style.cursor='grabbing';e.stopImmediatePropagation();},true);
  canvas.addEventListener('pointermove',e=>{pointerRay(e);if(state.drag?.id===e.pointerId){const p=new THREE.Vector3();if(!raycaster.ray.intersectPlane(state.drag.plane,p))return;const rect=canvas.getBoundingClientRect(),delta={x:(e.clientX-state.drag.lastX)/rect.width,y:(e.clientY-state.drag.lastY)/rect.height};state.drag.root.userData.motionController?.drag(p,delta);if(state.drag.root.userData.moveGrab){const deltaPosition=p.clone().sub(state.drag.startPoint);deltaPosition.clampLength(0,.85);p.copy(state.drag.startPoint).add(deltaPosition);state.drag.root.userData.moveGrab(p);}state.drag.lastX=e.clientX;state.drag.lastY=e.clientY;state.drag.point.copy(p);e.stopImmediatePropagation();}else{canvas.style.cursor=raycaster.intersectObjects(pickables,false).length?'grab':'default';}},true);
  canvas.addEventListener('pointerup',releasePointer,true);canvas.addEventListener('pointercancel',releasePointer,true);canvas.addEventListener('lostpointercapture',releasePointer,true);
}
function releasePointer(){if(!state.drag)return;const d=state.drag;state.drag=null;d.root.userData.motionController?.release();d.root.userData.releaseGrab?.();if(renderer.domElement.hasPointerCapture(d.id))renderer.domElement.releasePointerCapture(d.id);controls.enabled=true;renderer.domElement.style.cursor='default';$('#interaction-state').textContent='RELEASE / SETTLING';bus.emit('release',d.point,.5);}

function resize(){const rect=$('#viewport').getBoundingClientRect();if(!rect.width||!rect.height)return;camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();renderer.setSize(rect.width,rect.height,false);composer.setSize(rect.width,rect.height);}
function loop(){const dt=Math.min(clock.getDelta(),.04);renderFrame(dt);}
function renderFrame(dt){reflectionSerial++;if(state.motion)state.time+=dt;const simdt=state.motion?dt:0;
  if(cameraTween){cameraTween.time+=dt;const t=clamp(cameraTween.time/1.1,0,1),s=t*t*(3-2*t);camera.position.lerpVectors(cameraTween.start,cameraTween.end,s);controls.target.lerpVectors(cameraTween.from,cameraTween.to,s);if(t===1)cameraTween=null;}
  updateMaterials(materials,state.time,{point:new THREE.Vector3(),strength:0,velocity:new THREE.Vector3()});for(const m of motions)m.update(simdt,state.time);for(const a of animated){if(a.type==='float'){a.object.position.y=a.home.y+Math.sin(state.time*.65+a.phase)*.13;a.object.rotation.y=Math.sin(state.time*.25+a.phase)*.12;}else if(a.type==='custom')a.update(simdt);}
  if(environment)environment.children.forEach(o=>{if(o.userData.home){const h=o.userData.home,i=o.userData.phase;o.position.set(h.x+Math.sin(state.time*.18+i)*.25,h.y+Math.sin(state.time*.33+i)*.17,h.z+Math.cos(state.time*.21+i)*.24);}});
  if(water&&state.motion){const pos=water.geometry.attributes.position,a=pos.array,r=water.userData.rest;for(let i=0;i<a.length;i+=3){const x=r[i],z=r[i+2];a[i+1]=Math.sin(x*.48+state.time*.5)*.029+Math.cos(z*.61+state.time*.35)*.024+Math.sin((x+z)*1.4+state.time*.7)*.011;for(const impulse of waterImpulses){const t=state.time-impulse.start,d=Math.hypot(x-impulse.x,z-impulse.z),front=d-t*1.6;if(t<8)a[i+1]+=Math.cos(front*7)*Math.exp(-front*front*1.3)*Math.exp(-t*.65)*.075*impulse.strength;}}pos.needsUpdate=true;if(frameCount%3===0)water.geometry.computeVertexNormals();}
  if(caustics&&frameCount%3===0)caustics.update(state.time);transitionSystem?.update(simdt);if(!(transitionId==='L18'&&transitionHandle?.status==='running'))controls.update();composer.render();frameCount++;fpsClock+=dt;if(fpsClock>.8){state.fps=Math.round(frameCount/fpsClock);$('#performance').textContent=`${state.fps} FPS / LIVE 3D`;$('#stats').textContent=`${Math.round(renderer.info.render.triangles/1000)}K TRIANGLES / PERSPECTIVE`;frameCount=0;fpsClock=0;}
}

function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function exportPNG(){composer.render();renderer.domElement.toBlob(blob=>{if(blob){download(blob,`opaline-${state.mode}-${state.selected}-${state.theme}.png`);toast('PNG image exported');}},'image/png');}
async function exportGLB(){if(!selectedObject)return;const saved=[];try{
  // Interaction controllers contain back references. Export only portable authoring metadata.
  selectedObject.traverse(o=>{saved.push([o,o.userData]);o.userData={id:o.userData.elementId||o.userData.id,role:o.userData.role};});
  const copy=selectedObject.clone(true);for(const [o,data] of saved)o.userData=data;saved.length=0;copy.position.set(0,0,0);
  copy.traverse(o=>{if(!o.isMesh)return;const source=o.material;const m=new THREE.MeshPhysicalMaterial({color:source.color||0xbddacb,roughness:source.roughness??.18,transmission:source.transmission??.7,thickness:source.thickness??.5,ior:source.ior??1.42,metalness:source.metalness||0,clearcoat:source.clearcoat||0,side:source.side});if(source.emissive)m.emissive.copy(source.emissive);m.emissiveIntensity=source.emissiveIntensity||0;o.material=m;});
  const data=await new GLTFExporter().parseAsync(copy,{binary:true,onlyVisible:true});download(new Blob([data],{type:'model/gltf-binary'}),`opaline-${state.selected}-${state.theme}.glb`);copy.traverse(o=>{if(o.isMesh)o.material.dispose();});toast('GLB exported · motion remains in the runtime library');
}catch(e){for(const [o,data] of saved)o.userData=data;console.error(e);toast('GLB export failed. Source geometry remains available.');}}


init().catch(fail);
