import test from 'node:test';
import assert from 'node:assert/strict';
import {SoftBody,makeTetGrid,signedTetVolume,PBFFluid,makeParticleBlock,PhysicsWorld,PlaneCollider,SphereCollider,BoxCollider,ParticleSystem,ParticleCoupling,Cloth,Rod,makeClothGrid,makeRodPoints,createParticlePreset,createFieldPreset,ContactController,createContactRecipe} from '../src/physics/index.js';
const finite=a=>assert.ok(Array.from(a).every(Number.isFinite),'all numerical state is finite');
const near=(a,b,e=1e-5)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b} within ${e}`);
const gel=(opts={})=>new SoftBody({...makeTetGrid({nx:3,ny:2,nz:3,size:[.8,.4,.6],origin:[0,.5,0]}),gravity:[0,0,0],edgeCompliance:1e-7,volumeCompliance:1e-10,iterations:12,damping:3,...opts});

test('tetrahedral grid encloses the analytic box volume with a closed outward surface',()=>{const grid=makeTetGrid({nx:3,ny:2,nz:4,size:[.8,.4,.6]});let volume=0;for(let t=0;t<grid.tetrahedra.length;t+=4){const v=signedTetVolume(grid.positions,...grid.tetrahedra.subarray(t,t+4));assert.ok(v>0);volume+=v;}near(volume,.8*.4*.6,1e-7);const edges=new Map();for(let t=0;t<grid.surfaceIndices.length;t+=3){const f=grid.surfaceIndices.subarray(t,t+3);for(let a=0;a<3;a++){const k=[f[a],f[(a+1)%3]].sort((a,b)=>a-b).join(':');edges.set(k,(edges.get(k)||0)+1);}}assert.ok([...edges.values()].every(n=>n===2));});

test('XPBD edge and volume constraints recover compression without inversion',()=>{const body=gel();for(let i=0;i<body.count;i++)body.positions[3*i+1]=.5+(body.positions[3*i+1]-.5)*.65;assert.ok(body.volume<body.restVolume*.7);for(let i=0;i<240;i++)body.step(1/120);near(body.volume/body.restVolume,1,.003);assert.equal(body.invertedTetrahedra,0);finite(body.positions);});

test('local simultaneous grabs deform gel; cancellation retains a valid moving state',()=>{const body=gel();const low=Array.from({length:body.count},(_,i)=>i).filter(i=>body.positions[i*3+1]<.31);low.forEach(i=>body.pin(i));const high=Array.from({length:body.count},(_,i)=>i).filter(i=>body.positions[i*3+1]>.69);const left=high.filter(i=>body.positions[i*3]<0),right=high.filter(i=>body.positions[i*3]>=0);body.grab('left',left,[-.2,.58,0],1e-7);body.grab('right',right,[.2,.76,0],1e-7);for(let i=0;i<30;i++)body.step(1/120);const yL=left.reduce((s,i)=>s+body.positions[3*i+1],0)/left.length,yR=right.reduce((s,i)=>s+body.positions[3*i+1],0)/right.length;assert.ok(yR-yL>.07);low.forEach(i=>near(body.positions[3*i+1],.3,1e-6));body.cancelInteractions();assert.equal(body.grabs.size,0);for(let i=0;i<180;i++)body.step(1/120);finite(body.positions);near(body.volume/body.restVolume,1,.03);});

test('gel collisions prevent plane and sphere penetration',()=>{const floor=new PlaneCollider({offset:0}),sphere=new SphereCollider({center:[0,.25,0],radius:.12});const body=gel({gravity:[0,-9.81,0],colliders:[sphere,floor],radius:.01});for(let i=0;i<300;i++)body.step(1/120);for(let i=0;i<body.count;i++){const k=3*i;assert.ok(body.positions[k+1]>=.0099);assert.ok(Math.hypot(body.positions[k],body.positions[k+1]-.25,body.positions[k+2])>=.1299);}finite(body.velocities);});

test('fixed stepping gives identical states independent of frame chunking',()=>{const a=gel({gravity:[0,-1,0]}),b=gel({gravity:[0,-1,0]}),wa=new PhysicsWorld(),wb=new PhysicsWorld();wa.add(a);wb.add(b);for(let i=0;i<120;i++)wa.step(1/120);for(let i=0;i<60;i++)wb.step(1/60);assert.equal(wa.steps,120);assert.equal(wb.steps,120);assert.deepEqual(a.positions,b.positions);assert.deepEqual(a.velocities,b.velocities);});

test('timing overload is observable and backlog is retained',()=>{const w=new PhysicsWorld({fixedDt:.01,maxSubsteps:2,maxFrameDt:.1});w.step(.2);near(w.droppedTime,.1);near(w.backlogSeconds,.08);w.step(0);near(w.backlogSeconds,.06);});

test('PBF density constraints reduce a compressed block density error',()=>{const p=makeParticleBlock({nx:4,ny:4,nz:4,spacing:.06,origin:[0,.2,0]}),f=new PBFFluid({positions:p,smoothingRadius:.13,particleRadius:.018,iterations:10,gravity:[0,0,0],vorticity:0,artificialPressure:0});for(let i=0;i<f.count;i++)f.positions[3*i]*=.6;f.hash.build(f.positions,f.count);f._densityPass();const before=Math.max(...f.density.subarray(0,f.count))/f.restDensity-1;f.step(1/120);const after=Math.max(...f.density.subarray(0,f.count))/f.restDensity-1;assert.ok(before>.2);assert.ok(after<before*.35,`${before} -> ${after}`);finite(f.activePositions);});

test('liquid has finite 3D state inside collision boundaries for 240 substeps',()=>{const f=new PBFFluid({positions:makeParticleBlock({nx:4,ny:4,nz:4,origin:[0,.2,0]}),bounds:{min:[-.5,0,-.5],max:[.5,.9,.5]},particleRadius:.025,smoothingRadius:.14});const mass=f.mass;for(let i=0;i<240;i++)f.step(1/120);finite(f.activePositions);finite(f.velocities);near(f.mass,mass,0);for(let i=0;i<f.count;i++)for(let a=0;a<3;a++){const v=f.positions[3*i+a];assert.ok(v>=(a===1?.025:-.475)-1e-6);assert.ok(v<=(a===1?.875:.475)+1e-6);}});

test('particle transfer carries mass, velocity, pigment, and a complete ledger',()=>{const a=new PBFFluid({positions:[0,0,0,.05,0,0],particleMass:.25,capacity:8}),b=new PBFFluid({positions:[],particleMass:.25,capacity:8});a.pigment.set([.8,.2,.1],0);a.velocities.set([1,2,3],0);assert.ok(a.transferTo(b,0));near(a.mass+b.mass,.5);near(b.pigmentMass[0],.2);assert.deepEqual([...b.velocities.subarray(0,3)],[1,2,3]);a.inject([.2,0,0]);a.remove(0);for(const f of [a,b])near(f.mass,f.massLedger.initial+f.massLedger.injected-f.massLedger.removed,1e-8);});

test('pairwise diffusion conserves total pigment and viscosity conserves momentum',()=>{const f=new PBFFluid({positions:[-.025,0,0,.025,0,0],gravity:[0,0,0],artificialPressure:0,vorticity:0,damping:0,viscosity:5,pigmentDiffusion:8});f.pigment.set([1,0,.3,0,.4,.6]);f.velocities.set([-1,0,0,1,0,0]);const pigment=f.pigmentMass;for(let i=0;i<20;i++)f.step(1/1000);for(let a=0;a<3;a++)near(f.pigmentMass[a],pigment[a],1e-6);for(let a=0;a<3;a++)near(f.velocities[a]+f.velocities[3+a],0,1e-4);assert.ok(f.pigment[0]<1&&f.pigment[3]>0);});

test('two-body coupling transfers equal and opposite momentum',()=>{const a=new ParticleSystem({gravity:[0,0,0],drag:0}),b=new ParticleSystem({gravity:[0,0,0],drag:0});a.emit({position:[-.02,0,0],velocity:[1,0,0],radius:.03,mass:2});b.emit({position:[.02,0,0],velocity:[-1,0,0],radius:.03,mass:1});const c=new ParticleCoupling(a,b,{restitution:1,friction:0});c.step(1/120);near(2*a.velocities[0]+b.velocities[0],1,1e-6);near(a.velocities[0],-1/3,1e-6);near(b.velocities[0],5/3,1e-6);near(Math.abs(a.positions[0]-b.positions[0]),.06,1e-6);});

test('colliding peer particles conserve momentum and obey restitution',()=>{const p=new ParticleSystem({gravity:[0,0,0],drag:0,restitution:.5,friction:0});p.emit({position:[-.025,0,0],velocity:[1,0,0],radius:.03,mass:1});p.emit({position:[.025,0,0],velocity:[-1,0,0],radius:.03,mass:1});p.step(1/1000);near(p.velocities[0]+p.velocities[3],0);near(p.velocities[0],-.5);near(p.velocities[3],.5);});

test('pinned cloth responds in depth and retains edge lengths',()=>{const grid=makeClothGrid({nx:5,ny:5,size:[.5,.5],origin:[0,.5,0]}),c=new Cloth({...grid,gravity:[0,-1,0],aerodynamicWind:[0,0,1.5],damping:2,iterations:12});for(let i=30;i<36;i++)c.pin(i);for(let i=0;i<180;i++)c.step(1/120);finite(c.positions);assert.ok(Math.max(...Array.from(c.positions).filter((_,i)=>i%3===2))>.003);for(let i=30;i<36;i++)near(c.positions[3*i+1],.75,1e-6);for(let e=0;e<c.stretch.rest.length;e++){const ia=c.stretch.indices[2*e]*3,ib=c.stretch.indices[2*e+1]*3;const d=Math.hypot(c.positions[ia]-c.positions[ib],c.positions[ia+1]-c.positions[ib+1],c.positions[ia+2]-c.positions[ib+2]);assert.ok(Math.abs(d/c.stretch.rest[e]-1)<.04);}});

test('rod preserves chain lengths and fixed root under load',()=>{const r=new Rod({positions:makeRodPoints({count:12,length:.6,origin:[0,.3,0],direction:[1,0,0]}),gravity:[0,-2,0],iterations:16,damping:2});r.pin(0);for(let i=0;i<120;i++)r.step(1/120);finite(r.positions);near(r.positions[0],0);near(r.positions[1],.3,1e-6);assert.ok(r.positions[34]<.3);for(let e=0;e<r.stretch.rest.length;e++){const i=e*3,j=i+3,d=Math.hypot(r.positions[i]-r.positions[j],r.positions[i+1]-r.positions[j+1],r.positions[i+2]-r.positions[j+2]);assert.ok(Math.abs(d/r.stretch.rest[e]-1)<.05);}});

test('all 18 particle and 12 field presets produce finite deterministic state',()=>{for(let n=1;n<=18;n++){const id=`G${String(n).padStart(2,'0')}`,p=createParticlePreset(id,{count:16,seed:9});for(let t=0;t<12;t++)p.step(1/120);finite(p.positions);finite(p.orientations);for(let i=0;i<p.count;i++)near(Math.hypot(...p.orientations.subarray(i*4,i*4+4)),1,1e-6);}for(let n=1;n<=12;n++){const f=createFieldPreset(`H${String(n).padStart(2,'0')}`),out=[0,0,0];f.sample(.1,.2,.3,4,out);finite(out);}const a=createParticlePreset('G01',{count:10,seed:3}),b=createParticlePreset('G01',{count:10,seed:3});assert.deepEqual(a.positions,b.positions);});

test('invalid inputs fail explicitly rather than poisoning numerical state',()=>{assert.throws(()=>new PBFFluid({positions:[0,NaN,0]}));assert.throws(()=>new SoftBody({positions:[0,0,0,1,0,0,2,0,0,3,0,0],tetrahedra:[0,1,2,3]}));assert.throws(()=>new PhysicsWorld().step(-1));assert.throws(()=>new BoxCollider({min:[1,0,0],max:[0,1,1]}));});


test('contact recipes author different local constraints and release interrupted input',()=>{const a=gel(),b=gel();const pinch=new ContactController(a,'K04'),pull=new ContactController(b,'K05');for(let i=0;i<72;i++){pinch.update(1/120);pull.update(1/120);a.step(1/120);b.step(1/120);}assert.equal(a.grabs.size,2);assert.equal(b.grabs.size,1);assert.notDeepEqual(a.positions,b.positions);pinch.cancel();pull.cancel();assert.equal(a.grabs.size,0);assert.equal(b.grabs.size,0);const c=gel(),interrupted=new ContactController(c,'K23');for(let i=0;i<90;i++){interrupted.update(1/120);c.step(1/120);}assert.equal(c.grabs.size,0);finite(c.positions);assert.ok(createContactRecipe('K18').limitation.includes('not implemented'));});
