import {ConstraintBody,distanceConstraints,solveDistances,finiteArray} from './common.js';
/** Triangle sheet with XPBD structural/shear edges and hinge-opposite bend distances. */
export class Cloth extends ConstraintBody {
  constructor({triangles,stretchCompliance=1e-7,bendCompliance=2e-4,aerodynamicWind=[0,0,0],airDensity=1.225,dragCoefficient=.9,...options}={}){super(options);finiteArray(triangles,3,'triangles');this.surfaceIndices=new Uint32Array(triangles);this.triangles=this.surfaceIndices;this.stretchCompliance=stretchCompliance;this.bendCompliance=bendCompliance;this.aerodynamicWind=[...aerodynamicWind];this.airDensity=airDensity;this.dragCoefficient=dragCoefficient;const edges=new Map(),bend=[];for(let t=0;t<triangles.length;t+=3){const q=Array.from(triangles.slice(t,t+3));q.forEach(i=>this.checkIndex(i));for(let j=0;j<3;j++){const a=q[j],b=q[(j+1)%3],opp=q[(j+2)%3],key=[a,b].sort((a,b)=>a-b).join(':');if(edges.has(key)){const e=edges.get(key);bend.push([e.opposite,opp]);}else edges.set(key,{pair:[a,b],opposite:opp});}}this.stretch=distanceConstraints(this.positions,[...edges.values()].map(e=>e.pair));this.bend=distanceConstraints(this.positions,bend);}
  _aerodynamics(dt){const p=this.positions,v=this.velocities,wind=this.aerodynamicWind;for(let t=0;t<this.triangles.length;t+=3){const ids=this.triangles.subarray(t,t+3),a=3*ids[0],b=3*ids[1],c=3*ids[2],ux=p[b]-p[a],uy=p[b+1]-p[a+1],uz=p[b+2]-p[a+2],vx=p[c]-p[a],vy=p[c+1]-p[a+1],vz=p[c+2]-p[a+2],n=[uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx],area2=Math.hypot(...n);if(area2<1e-10)continue;for(let k=0;k<3;k++)n[k]/=area2;let normalSpeed=0;for(let k=0;k<3;k++)normalSpeed+=(wind[k]-(v[a+k]+v[b+k]+v[c+k])/3)*n[k];const force=.5*this.airDensity*this.dragCoefficient*area2*.5*normalSpeed*Math.abs(normalSpeed);for(const i of ids)for(let k=0;k<3;k++)v[3*i+k]+=n[k]*force/3*this.inverseMass[i]*dt;}}
  step(dt){this._aerodynamics(dt);this._begin(dt);this.stretch.lambda.fill(0);this.bend.lambda.fill(0);for(let it=0;it<this.iterations;it++){solveDistances(this,this.stretch,this.stretchCompliance,dt);solveDistances(this,this.bend,this.bendCompliance,dt);this._solveGrabs(dt);this._collide();this._applyPins();}this._finish(dt);return this;}
}
export class Rod extends ConstraintBody {
  constructor({stretchCompliance=1e-8,bendCompliance=1e-5,closed=false,...options}={}){super(options);this.stretchCompliance=stretchCompliance;this.bendCompliance=bendCompliance;this.closed=closed;const edges=[],bend=[];for(let i=0;i<this.count-1;i++)edges.push([i,i+1]);for(let i=0;i<this.count-2;i++)bend.push([i,i+2]);if(closed&&this.count>2){edges.push([this.count-1,0]);bend.push([this.count-2,0],[this.count-1,1]);}this.stretch=distanceConstraints(this.positions,edges);this.bend=distanceConstraints(this.positions,bend);}
  step(dt){this._begin(dt);this.stretch.lambda.fill(0);this.bend.lambda.fill(0);for(let it=0;it<this.iterations;it++){solveDistances(this,this.stretch,this.stretchCompliance,dt);solveDistances(this,this.bend,this.bendCompliance,dt);this._solveGrabs(dt);this._collide();this._applyPins();}this._finish(dt);return this;}
}
export function makeClothGrid({nx=16,ny=16,size=[1,1],origin=[0,0,0],plane='xy'}={}){const p=[],tri=[];for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++){const a=(x/nx-.5)*size[0],b=(y/ny-.5)*size[1];p.push(origin[0]+a,origin[1]+(plane==='xy'?b:0),origin[2]+(plane==='xz'?b:0));}for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const a=x+y*(nx+1),b=a+1,c=a+nx+1,d=c+1;tri.push(a,b,d,a,d,c);}return {positions:new Float32Array(p),triangles:new Uint32Array(tri)};}
export function makeRodPoints({count=24,length=1,origin=[0,0,0],direction=[0,1,0],curl=0}={}){const p=new Float32Array(count*3),norm=Math.hypot(...direction);for(let i=0;i<count;i++){const t=i/(count-1);p[3*i]=origin[0]+direction[0]/norm*t*length+Math.sin(t*Math.PI*2)*curl;p[3*i+1]=origin[1]+direction[1]/norm*t*length;p[3*i+2]=origin[2]+direction[2]/norm*t*length+(1-Math.cos(t*Math.PI*2))*curl;}return p;}
