import {BoxCollider,SpatialHash,finiteArray,validDt,resolveContactVelocity,EPS,clamp} from './common.js';
/** Position-based incompressibility in a genuine 3D particle domain. */
export class PBFFluid {
  constructor({positions,capacity,particleRadius=.025,smoothingRadius=.12,restDensity=1000,particleMass,iterations=5,gravity=[0,-9.81,0],bounds,colliders=[],viscosity=.2,pigmentDiffusion=.08,vorticity=.015,artificialPressure=.0003,lambdaEpsilon=1e-6,damping=.04,fields=[]}={}){
    finiteArray(positions,3,'positions');this.count=positions.length/3;this.capacity=capacity??Math.max(this.count*2,256);if(this.capacity<this.count||!Number.isInteger(this.capacity))throw new RangeError('capacity must hold all particles');if(!(smoothingRadius>0&&particleRadius>0&&restDensity>0))throw new RangeError('positive fluid dimensions and density required');
    this.positions=new Float32Array(this.capacity*3);this.positions.set(positions);this.velocities=new Float32Array(this.capacity*3);this.previous=new Float32Array(this.capacity*3);this.beforeVelocity=new Float32Array(this.capacity*3);this.pigment=new Float32Array(this.capacity*3);this.delta=new Float32Array(this.capacity*3);this.omega=new Float32Array(this.capacity*3);this.density=new Float32Array(this.capacity);this.lambda=new Float32Array(this.capacity);
    this.particleRadius=particleRadius;this.radius=particleRadius;this.h=smoothingRadius;this.h2=this.h*this.h;this.poly6=315/(64*Math.PI*this.h**9);this.spiky=-45/(Math.PI*this.h**6);this.restDensity=restDensity;this.iterations=iterations;this.gravity=[...gravity];this.colliders=[...colliders];if(bounds)this.colliders.unshift(new BoxCollider({...bounds,inside:true}));this.viscosity=viscosity;this.pigmentDiffusion=pigmentDiffusion;this.vorticity=vorticity;this.artificialPressure=artificialPressure;this.lambdaEpsilon=lambdaEpsilon;this.damping=damping;this.fields=[...fields];this.hash=new SpatialHash(this.h);this._neighbors=[];this._force=[0,0,0];this.time=0;this.contacts=new Map();this.correctionClamps=0;this.hash.build(this.positions,this.count);
    let maxKernel=0;for(let i=0;i<this.count;i++){const k=i*3;this.hash.query(...this.positions.subarray(k,k+3),this._neighbors);let rho=0;for(const j of this._neighbors){const l=j*3;rho+=this.kernel((this.positions[k]-this.positions[l])**2+(this.positions[k+1]-this.positions[l+1])**2+(this.positions[k+2]-this.positions[l+2])**2);}maxKernel=Math.max(maxKernel,rho);}this.particleMass=particleMass??restDensity/Math.max(maxKernel,this.kernel(0));if(!(this.particleMass>0))throw new RangeError('particleMass must be positive');this.massLedger={initial:this.count*this.particleMass,injected:0,removed:0};
  }
  kernel(r2){return r2>=this.h2?0:this.poly6*(this.h2-r2)**3;}
  get mass(){return this.count*this.particleMass;}
  get activePositions(){return this.positions.subarray(0,this.count*3);}
  get pigmentMass(){const sum=[0,0,0];for(let i=0;i<this.count;i++)for(let a=0;a<3;a++)sum[a]+=this.pigment[3*i+a]*this.particleMass;return sum;}
  inject(position,velocity=[0,0,0],pigment=[0,0,0]){if(this.count===this.capacity)return -1;finiteArray(position,3,'position');finiteArray(velocity,3,'velocity');const i=this.count++;for(let a=0;a<3;a++){this.positions[3*i+a]=position[a];this.previous[3*i+a]=position[a];this.velocities[3*i+a]=velocity[a];this.pigment[3*i+a]=clamp(pigment[a],0,1);}this.massLedger.injected+=this.particleMass;return i;}
  remove(index){if(!Number.isInteger(index)||index<0||index>=this.count)throw new RangeError('particle index out of range');const k=index*3,last=(this.count-1)*3,result={mass:this.particleMass,position:Array.from(this.positions.subarray(k,k+3)),velocity:Array.from(this.velocities.subarray(k,k+3)),pigment:Array.from(this.pigment.subarray(k,k+3))};for(const array of [this.positions,this.previous,this.velocities,this.pigment])for(let a=0;a<3;a++){array[k+a]=array[last+a];array[last+a]=0;}this.count--;this.massLedger.removed+=this.particleMass;return result;}
  transferTo(target,index){if(target.capacity===target.count) return false;if(Math.abs(target.particleMass-this.particleMass)>1e-8)throw new RangeError('transfer requires equal particle mass');const k=3*index;if(!Number.isInteger(index)||index<0||index>=this.count)throw new RangeError('particle index out of range');target.inject(this.positions.subarray(k,k+3),this.velocities.subarray(k,k+3),this.pigment.subarray(k,k+3));this.remove(index);return true;}
  addImpulse(point,radius,impulse){if(!(radius>0))throw new RangeError('impulse radius must be positive');finiteArray(impulse,3,'impulse');const weights=new Float32Array(this.count);let sum=0;for(let i=0;i<this.count;i++){const k=3*i;weights[i]=Math.max(0,1-Math.hypot(this.positions[k]-point[0],this.positions[k+1]-point[1],this.positions[k+2]-point[2])/radius);sum+=weights[i];}if(sum>0)for(let i=0;i<this.count;i++)for(let a=0;a<3;a++)this.velocities[3*i+a]+=impulse[a]*weights[i]/(sum*this.particleMass);}
  _collide(){for(let i=0;i<this.count;i++)for(let c=0;c<this.colliders.length;c++){const hit=this.colliders[c].project(this.positions,3*i,this.particleRadius);if(hit)this.contacts.set(`${i}:${c}`,{i,...hit});}}
  _densityPass(){const p=this.positions,mr=this.particleMass/this.restDensity;for(let i=0;i<this.count;i++){const k=i*3;this.hash.query(p[k],p[k+1],p[k+2],this._neighbors);let rho=0,gx=0,gy=0,gz=0,sum=0;for(const j of this._neighbors){const l=j*3,x=p[k]-p[l],y=p[k+1]-p[l+1],z=p[k+2]-p[l+2],r2=x*x+y*y+z*z;if(r2>=this.h2)continue;rho+=this.particleMass*this.kernel(r2);if(j===i||r2<EPS)continue;const r=Math.sqrt(r2),g=mr*this.spiky*(this.h-r)**2/r,dx=g*x,dy=g*y,dz=g*z;gx+=dx;gy+=dy;gz+=dz;sum+=dx*dx+dy*dy+dz*dz;}this.density[i]=rho;sum+=gx*gx+gy*gy+gz*gz;const C=Math.max(0,rho/this.restDensity-1);this.lambda[i]=-C/(sum+this.lambdaEpsilon);}}
  _correctionPass(){const p=this.positions,mr=this.particleMass/this.restDensity,Wq=this.kernel((.3*this.h)**2);this.delta.fill(0,0,this.count*3);for(let i=0;i<this.count;i++){const k=i*3;this.hash.query(p[k],p[k+1],p[k+2],this._neighbors);for(const j of this._neighbors){if(i===j)continue;const l=j*3,x=p[k]-p[l],y=p[k+1]-p[l+1],z=p[k+2]-p[l+2],r2=x*x+y*y+z*z;if(r2>=this.h2||r2<EPS)continue;const r=Math.sqrt(r2),sc=-this.artificialPressure*(this.kernel(r2)/Wq)**4,g=mr*(this.lambda[i]+this.lambda[j]+sc)*this.spiky*(this.h-r)**2/r;this.delta[k]+=g*x;this.delta[k+1]+=g*y;this.delta[k+2]+=g*z;}const len=Math.hypot(this.delta[k],this.delta[k+1],this.delta[k+2]),max=.2*this.h;if(len>max){this.correctionClamps++;for(let a=0;a<3;a++)this.delta[k+a]*=max/len;}}for(let k=0;k<this.count*3;k++)p[k]+=this.delta[k];}
  _diffuse(dt){const p=this.positions,n=this.count,W0=this.kernel(0),pairs=[];let maxDegree=1;const degree=new Uint32Array(n);for(let i=0;i<n;i++){const k=3*i;this.hash.query(p[k],p[k+1],p[k+2],this._neighbors);for(const j of this._neighbors){if(j<=i)continue;const l=3*j,r2=(p[k]-p[l])**2+(p[k+1]-p[l+1])**2+(p[k+2]-p[l+2])**2;if(r2>=this.h2)continue;pairs.push([i,j,this.kernel(r2)/W0]);degree[i]++;degree[j]++;}}for(let i=0;i<n;i++)maxDegree=Math.max(maxDegree,degree[i]);for(const [array,rate] of [[this.velocities,this.viscosity],[this.pigment,this.pigmentDiffusion]]){if(rate<=0)continue;this.delta.fill(0,0,n*3);const coeff=(1-Math.exp(-rate*dt))/maxDegree;for(const [i,j,w] of pairs)for(let a=0;a<3;a++){const d=(array[3*j+a]-array[3*i+a])*w*coeff;this.delta[3*i+a]+=d;this.delta[3*j+a]-=d;}for(let k=0;k<n*3;k++)array[k]+=this.delta[k];}}
  _vorticity(dt){if(this.vorticity<=0)return;const p=this.positions,v=this.velocities,o=this.omega; o.fill(0,0,this.count*3);for(let i=0;i<this.count;i++){const k=3*i;this.hash.query(p[k],p[k+1],p[k+2],this._neighbors);for(const j of this._neighbors){if(i===j)continue;const l=3*j,x=p[k]-p[l],y=p[k+1]-p[l+1],z=p[k+2]-p[l+2],r=Math.hypot(x,y,z);if(r<EPS||r>=this.h)continue;const s=this.particleMass/Math.max(this.density[j],this.restDensity*.1)*this.spiky*(this.h-r)**2/r,gx=x*s,gy=y*s,gz=z*s,dx=v[l]-v[k],dy=v[l+1]-v[k+1],dz=v[l+2]-v[k+2];o[k]+=dy*gz-dz*gy;o[k+1]+=dz*gx-dx*gz;o[k+2]+=dx*gy-dy*gx;}}
    this.delta.fill(0,0,this.count*3);for(let i=0;i<this.count;i++){const k=3*i,om=Math.hypot(o[k],o[k+1],o[k+2]);let ex=0,ey=0,ez=0;this.hash.query(p[k],p[k+1],p[k+2],this._neighbors);for(const j of this._neighbors){if(i===j)continue;const l=3*j,x=p[k]-p[l],y=p[k+1]-p[l+1],z=p[k+2]-p[l+2],r=Math.hypot(x,y,z);if(r<EPS||r>=this.h)continue;const s=this.particleMass/Math.max(this.density[j],this.restDensity*.1)*(Math.hypot(o[l],o[l+1],o[l+2])-om)*this.spiky*(this.h-r)**2/r;ex+=x*s;ey+=y*s;ez+=z*s;}const len=Math.hypot(ex,ey,ez);if(len>EPS){const s=this.vorticity*dt/len;this.delta[k]=s*(ey*o[k+2]-ez*o[k+1]);this.delta[k+1]=s*(ez*o[k]-ex*o[k+2]);this.delta[k+2]=s*(ex*o[k+1]-ey*o[k]);}}for(let k=0;k<this.count*3;k++)v[k]+=this.delta[k];}
  step(dt){validDt(dt);this.previous.set(this.positions);this.contacts.clear();const decay=Math.exp(-this.damping*dt);for(let i=0;i<this.count;i++){const k=3*i;for(let a=0;a<3;a++)this.velocities[k+a]=(this.velocities[k+a]+this.gravity[a]*dt)*decay;for(const field of this.fields){this._force.fill(0);field.sample(this.positions[k],this.positions[k+1],this.positions[k+2],this.time,this._force);for(let a=0;a<3;a++)this.velocities[k+a]+=this._force[a]*dt;}for(let a=0;a<3;a++)this.positions[k+a]+=this.velocities[k+a]*dt;}this.beforeVelocity.set(this.velocities);this._collide();for(let it=0;it<this.iterations;it++){this.hash.build(this.positions,this.count);this._densityPass();this._correctionPass();this._collide();}for(let k=0;k<this.count*3;k++)this.velocities[k]=(this.positions[k]-this.previous[k])/dt;this.hash.build(this.positions,this.count);this._densityPass();this._diffuse(dt);this._vorticity(dt);for(const c of this.contacts.values())resolveContactVelocity(this.velocities,3*c.i,this.beforeVelocity,c);this.time+=dt;return this;}
}
export function makeParticleBlock({nx=8,ny=8,nz=8,spacing=.075,origin=[0,0,0]}={}){const p=new Float32Array(nx*ny*nz*3);let k=0;for(let y=0;y<ny;y++)for(let z=0;z<nz;z++)for(let x=0;x<nx;x++){p[k++]=origin[0]+(x-(nx-1)/2)*spacing;p[k++]=origin[1]+y*spacing;p[k++]=origin[2]+(z-(nz-1)/2)*spacing;}return p;}
