import {ConstraintBody, distanceConstraints, solveDistances, finiteArray, EPS} from './common.js';
export function signedTetVolume(p,a,b,c,d){a*=3;b*=3;c*=3;d*=3;const bx=p[b]-p[a],by=p[b+1]-p[a+1],bz=p[b+2]-p[a+2],cx=p[c]-p[a],cy=p[c+1]-p[a+1],cz=p[c+2]-p[a+2],dx=p[d]-p[a],dy=p[d+1]-p[a+1],dz=p[d+2]-p[a+2];return (bx*(cy*dz-cz*dy)+by*(cz*dx-cx*dz)+bz*(cx*dy-cy*dx))/6;}
export function tetrahedralSurface(tetrahedra,positions){const map=new Map();for(let t=0;t<tetrahedra.length;t+=4){const v=Array.from(tetrahedra.subarray(t,t+4));for(let omit=0;omit<4;omit++){const f=v.filter((_,j)=>j!==omit),key=[...f].sort((a,b)=>a-b).join(':');if(map.has(key)){map.delete(key);continue;}if(signedTetVolume(positions,...f,v[omit])>0)[f[1],f[2]]=[f[2],f[1]];map.set(key,f);}}return new Uint32Array([...map.values()].flat());}
/** A uniform hexahedral grid split into six conforming tetrahedra per cell. */
export function makeTetGrid({nx=5,ny=3,nz=5,size=[1,.45,1],origin=[0,0,0],shape='box'}={}){for(const n of [nx,ny,nz])if(!Number.isInteger(n)||n<1)throw new RangeError('nx, ny and nz are positive cell counts');const p=[],t=[],idx=(x,y,z)=>x+(nx+1)*(y+(ny+1)*z);for(let z=0;z<=nz;z++)for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++){let q=[2*x/nx-1,2*y/ny-1,2*z/nz-1];if(shape==='ellipsoid'){const [a,b,c]=q;q=[a*Math.sqrt(1-b*b/2-c*c/2+b*b*c*c/3),b*Math.sqrt(1-c*c/2-a*a/2+c*c*a*a/3),c*Math.sqrt(1-a*a/2-b*b/2+a*a*b*b/3)];}for(let a=0;a<3;a++)p.push(origin[a]+q[a]*size[a]/2);}const ring=[1,3,2,6,4,5];for(let z=0;z<nz;z++)for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const v=[];for(let dz=0;dz<=1;dz++)for(let dy=0;dy<=1;dy++)for(let dx=0;dx<=1;dx++)v.push(idx(x+dx,y+dy,z+dz));for(let a=0;a<6;a++){const q=[v[0],v[ring[a]],v[ring[(a+1)%6]],v[7]];if(signedTetVolume(p,...q)<0)[q[1],q[2]]=[q[2],q[1]];t.push(...q);}}const positions=new Float32Array(p),tetrahedra=new Uint32Array(t);return {positions,tetrahedra,surfaceIndices:tetrahedralSurface(tetrahedra,positions)};}
export class SoftBody extends ConstraintBody {
  constructor({tetrahedra,edgeCompliance=2e-5,volumeCompliance=1e-9,...options}={}){super(options);finiteArray(tetrahedra,4,'tetrahedra');this.tetrahedra=new Uint32Array(tetrahedra);this.restPositions=new Float32Array(this.positions);this.edgeCompliance=edgeCompliance;this.volumeCompliance=volumeCompliance;this.restVolumes=new Float32Array(tetrahedra.length/4);this.volumeLambda=new Float32Array(this.restVolumes.length);this._gradient=new Float64Array(12);const edges=new Map();for(let t=0;t<tetrahedra.length;t+=4){const v=Array.from(tetrahedra.slice(t,t+4));v.forEach(i=>this.checkIndex(i));const volume=signedTetVolume(this.positions,...v);if(Math.abs(volume)<1e-12)throw new RangeError(`degenerate tetrahedron ${t/4}`);this.restVolumes[t/4]=volume;for(let a=0;a<4;a++)for(let b=a+1;b<4;b++){const lo=Math.min(v[a],v[b]),hi=Math.max(v[a],v[b]);edges.set(`${lo}:${hi}`,[lo,hi]);}}this.edges=distanceConstraints(this.positions,[...edges.values()]);this.surfaceIndices=tetrahedralSurface(this.tetrahedra,this.positions);}
  get volume(){let v=0;for(let t=0;t<this.tetrahedra.length;t+=4)v+=Math.abs(signedTetVolume(this.positions,...this.tetrahedra.subarray(t,t+4)));return v;}
  get restVolume(){return this.restVolumes.reduce((s,v)=>s+Math.abs(v),0);}
  get invertedTetrahedra(){let n=0;for(let t=0;t<this.restVolumes.length;t++)if(signedTetVolume(this.positions,...this.tetrahedra.subarray(t*4,t*4+4))*this.restVolumes[t]<=0)n++;return n;}
  _solveVolumes(dt){const p=this.positions,w=this.inverseMass,g=this._gradient,alpha=this.volumeCompliance/(dt*dt);for(let t=0;t<this.restVolumes.length;t++){const ids=this.tetrahedra.subarray(4*t,4*t+4),a=3*ids[0],b=3*ids[1],c=3*ids[2],d=3*ids[3];const bx=p[b]-p[a],by=p[b+1]-p[a+1],bz=p[b+2]-p[a+2],cx=p[c]-p[a],cy=p[c+1]-p[a+1],cz=p[c+2]-p[a+2],dx=p[d]-p[a],dy=p[d+1]-p[a+1],dz=p[d+2]-p[a+2];g[3]=(cy*dz-cz*dy)/6;g[4]=(cz*dx-cx*dz)/6;g[5]=(cx*dy-cy*dx)/6;g[6]=(dy*bz-dz*by)/6;g[7]=(dz*bx-dx*bz)/6;g[8]=(dx*by-dy*bx)/6;g[9]=(by*cz-bz*cy)/6;g[10]=(bz*cx-bx*cz)/6;g[11]=(bx*cy-by*cx)/6;for(let k=0;k<3;k++)g[k]=-g[3+k]-g[6+k]-g[9+k];let denom=alpha;for(let j=0;j<4;j++)for(let k=0;k<3;k++)denom+=w[ids[j]]*g[j*3+k]**2;if(denom<EPS)continue;const volume=bx*g[3]+by*g[4]+bz*g[5],dl=(-(volume-this.restVolumes[t])-alpha*this.volumeLambda[t])/denom;this.volumeLambda[t]+=dl;for(let j=0;j<4;j++)for(let k=0;k<3;k++)p[ids[j]*3+k]+=w[ids[j]]*g[j*3+k]*dl;}}
  step(dt){this._begin(dt);this.edges.lambda.fill(0);this.volumeLambda.fill(0);for(let it=0;it<this.iterations;it++){solveDistances(this,this.edges,this.edgeCompliance,dt);this._solveVolumes(dt);this._solveGrabs(dt);this._collide();this._applyPins();}this._finish(dt);return this;}
  /** Renderer-independent radial impulse; impulse is total momentum shared by selected vertices. */
  addImpulse(point,radius,impulse){if(!(radius>0))throw new RangeError('impulse radius must be positive');finiteArray(impulse,3,'impulse');let total=0;const weights=new Float32Array(this.count);for(let i=0;i<this.count;i++){const k=3*i,d=Math.hypot(this.positions[k]-point[0],this.positions[k+1]-point[1],this.positions[k+2]-point[2]);weights[i]=Math.max(0,1-d/radius);total+=weights[i];}if(total>0)for(let i=0;i<this.count;i++)for(let a=0;a<3;a++)this.velocities[3*i+a]+=impulse[a]*weights[i]/total*this.inverseMass[i];}
}
